# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingDay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(max_length=100)),
                ('totalvotes', models.IntegerField(default=0)),
                ('vote1', models.IntegerField(default=0)),
                ('vote2', models.IntegerField(default=0)),
                ('vote3', models.IntegerField(default=0)),
                ('vote4', models.IntegerField(default=0)),
                ('vote5', models.IntegerField(default=0)),
                ('vote6', models.IntegerField(default=0)),
                ('vote7', models.IntegerField(default=0)),
                ('vote8', models.IntegerField(default=0)),
                ('vote9', models.IntegerField(default=0)),
                ('vote10', models.IntegerField(default=0)),
                ('vote11', models.IntegerField(default=0)),
                ('vote12', models.IntegerField(default=0)),
                ('vote13', models.IntegerField(default=0)),
                ('vote14', models.IntegerField(default=0)),
                ('vote15', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='votes',
            name='partyname',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
